version: 1
formatters:
  default_console_thread:
    (): yolo_models.log_set.utc_formatter.UTCFormatter
    format: '%(asctime)s %(levelname)s %(threadName)s %(module)s %(funcName)s %(message)s'
  default_console_process:
    (): yolo_models.log_set.utc_formatter.UTCFormatter
    format: '%(asctime)s %(levelname)s %(processName)s %(module)s %(funcName)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default_console_thread
    stream: ext://sys.stdout
loggers:
  server_processing:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]